import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';
import './AiInsights.css';

// "2026-07-06T09:14:00Z" -> "Jul 6, 9:14 AM"
const fmtTimestamp = (iso) =>
  new Intl.DateTimeFormat('en', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit'
  }).format(new Date(iso));

// The summary is plain text: a short overview, then "- " bullet lines.
function SummaryText({ text }) {
  const lines = text.split('\n').filter((l) => l.trim());
  const prose = lines.filter((l) => !l.trim().startsWith('- '));
  const bullets = lines.filter((l) => l.trim().startsWith('- ')).map((l) => l.trim().slice(2));
  return (
    <>
      {prose.map((p, i) => (
        <p key={i} className="ai-insights-text">{p}</p>
      ))}
      {bullets.length > 0 && (
        <ul className="ai-insights-bullets">
          {bullets.map((b, i) => (
            <li key={i}>{b}</li>
          ))}
        </ul>
      )}
    </>
  );
}

export default function AiInsights() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [failed, setFailed] = useState(false);
  const [notice, setNotice] = useState('');

  const load = useCallback(async (refresh) => {
    setNotice('');
    if (refresh) setRefreshing(true);
    try {
      const result = await api.getAiInsights(refresh);
      setData(result);
      setFailed(false);
      if (result.rateLimited) {
        setNotice('Just refreshed — try again in a few minutes.');
      } else if (result.stale) {
        setNotice("Couldn't fetch fresh insights — showing the last summary.");
      }
    } catch {
      setFailed(true);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    load(false);
  }, [load]);

  // AI features are off, or the account isn't connected yet: no card at all.
  if (!loading && !failed && (data?.enabled === false || data?.reason === 'not-connected')) {
    return null;
  }

  return (
    <section className="ai-insights card" aria-label="AI insights">
      <div className="ai-insights-head">
        <h2>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path
              d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9L12 3zM19 15l.95 2.55L22.5 18.5l-2.55.95L19 22l-.95-2.55-2.55-.95 2.55-.95L19 15z"
              fill="currentColor"
            />
          </svg>
          AI Insights
        </h2>
        {data?.available && (
          <div className="ai-insights-meta">
            <span className="ai-insights-updated">Updated {fmtTimestamp(data.generatedAt)}</span>
            <button
              type="button"
              className="ai-insights-refresh"
              onClick={() => load(true)}
              disabled={refreshing}
            >
              {refreshing ? 'Refreshing…' : 'Refresh'}
            </button>
          </div>
        )}
      </div>

      {loading && (
        <div className="ai-insights-skeleton" aria-hidden="true">
          <div className="skeleton ai-skeleton-line" style={{ width: '92%' }} />
          <div className="skeleton ai-skeleton-line" style={{ width: '78%' }} />
          <div className="skeleton ai-skeleton-line" style={{ width: '55%' }} />
        </div>
      )}

      {!loading && (failed || data?.available === false) && (
        <p className="ai-insights-unavailable">
          Insights unavailable right now. Your numbers below are unaffected — try again later.
        </p>
      )}

      {!loading && data?.available && (
        <>
          <SummaryText text={data.summary} />
          {notice && <p className="ai-insights-notice">{notice}</p>}
          <p className="ai-insights-footnote">
            Generated by AI from your {data.cadence === 'daily' ? 'last 7 days' : 'last 30 days'} of
            ad data — check the numbers below before acting on it.
          </p>
        </>
      )}
    </section>
  );
}
